import Layout from "@/components/Layout";

export const metadata = {
  title: "Salary Man",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <>
      <Layout />
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
        {children}
      </div>
    </>
  );
}
